pub const ANDROID_FB_ADDR: u64 = 0x200000;
pub const ANDROID_CMD_ADDR: u64 = 0x200100;

pub const AndroidCmd = extern struct {
    activity_ptr: u64,
    window_ptr: u64,
    input_queue_ptr: u64,
    has_window: u32,
    has_focus: u32,
    should_finish: u32,
    fb_width: u32,
    fb_height: u32,
    fb_stride: u32,
    fb_pixels: u64,
    touch_x: f32,
    touch_y: f32,
    touch_down: u32,
    touch_action: u32,
    touch_pointer_id: u32,
    key_action: u32,
    key_code: u32,
    lock_fn: u64,
    unlock_fn: u64,
    get_event_fn: u64,
    finish_event_fn: u64,
    get_event_type_fn: u64,
    get_action_fn: u64,
    get_x_fn: u64,
    get_y_fn: u64,
    get_keycode_fn: u64,
    present_fn: u64,
    touch_count: u32,
    touch_x_arr: [16]f32,
    touch_y_arr: [16]f32,
    touch_down_arr: [16]u32,
    touch_id_arr: [16]u32,
    clicked: u32,
    click_x: f32,
    click_y: f32,
};

pub const AndroidFb = struct {
    pixels: [800 * 600 * 4]u8,
};

pub fn initCmd() AndroidCmd {
    return AndroidCmd{
        .activity_ptr = 0,
        .window_ptr = 0,
        .input_queue_ptr = 0,
        .has_window = 0,
        .has_focus = 0,
        .should_finish = 0,
        .fb_width = 0,
        .fb_height = 0,
        .fb_stride = 0,
        .fb_pixels = 0,
        .touch_x = 0,
        .touch_y = 0,
        .touch_down = 0,
        .touch_action = 0,
        .touch_pointer_id = 0,
        .key_action = 0,
        .key_code = 0,
        .lock_fn = 0,
        .unlock_fn = 0,
        .get_event_fn = 0,
        .finish_event_fn = 0,
        .get_event_type_fn = 0,
        .get_action_fn = 0,
        .get_x_fn = 0,
        .get_y_fn = 0,
        .get_keycode_fn = 0,
        .present_fn = 0,
        .touch_count = 0,
        .touch_x_arr = [_]f32{0} ** 16,
        .touch_y_arr = [_]f32{0} ** 16,
        .touch_down_arr = [_]u32{0} ** 16,
        .touch_id_arr = [_]u32{0} ** 16,
        .clicked = 0,
        .click_x = 0,
        .click_y = 0,
    };
}
